In [1]:
import random
import numpy as np
from collections import Counter
import math

In [2]:
# Chapter 6

def allSumsOf(n):
    bm = [True] * len(n)
    bms = []
    sums = []
    for i in np.arange(2 ** len(n)) * 2:
        for j in np.arange(1,len(n)+1):
            if i%(2**j)==0:
                bm[j-1] = not bm[j-1]
        bms.append(bm[:])
        sums.append(np.sum(n[bm]))
    bms = np.array(bms)
    #print(bms)
    sums.sort()
    return sums
def allConsecSumsOf(n):
    bm = [True] * len(n)
    bms = []
    sums = []
    for i in np.arange(2 ** len(n)) * 2:
        for j in np.arange(1,len(n)+1):
            if i%(2**j)==0:
                bm[j-1] = not bm[j-1]
        noLongerConsec = False
        trueRun = False
        failed = False
        for i in range(len(bm)):
            if bm[i]:
                trueRun = True
            if trueRun and not bm[i]:
                noLongerConsec = True
            if noLongerConsec and bm[i]:
                failed = True
        if not failed:
            bms.append(bm[:])
            sums.append(np.sum(n[bm]))
    bms = np.array(bms)
    #print(bms)
    sums.sort()
    return sums
def canFindSumInSubarray(arr, s, start, end):
    res = False
    for j in range(end-start+1):
        for i in range(end-(start+j)+1):
            #print(np.sum(np.array(arr[start+j:start+j+i])))
            if np.sum(np.array(arr[start+j:start+j+i]))==s:
                res = True
    return res

# Chapter 7

def isLowerThan(c1, c2):
    if c1[1]==c2[1]:
        return c1[0]<c2[0]
    else:
        return c1[1]<c2[1]
def checkIfValidArrangement(hand, arr):
    newHand = [[0]*2]*5
    for i in range(len(arr)):
        newHand[i] = hand[arr[i]]
    if newHand[0][1] != newHand[1][1]:
        return False
    lc = 2
    if isLowerThan(newHand[2], newHand[3]):
        lc -= 1
    if isLowerThan(newHand[2], newHand[4]):
        lc -= 1
    rc = 2
    if isLowerThan(newHand[3], newHand[4]):
        rc -= 1
    steps = 2 * lc + rc
    return newHand[0][0] == ((newHand[1][0] + steps) % 13)

In [3]:
t = set([])
tries = 0
while len(t) < 10 and tries < 1000000:
    tries += 1
    t.add(random.randint(10,99))
    s = list(t)
    s.sort()
    s = np.array(s)
    d = np.diff(s)
    if len(set(d)) != len(d):
        t = set([])
    #if canFindConsecsWithSpaceBetween():
print(tries)
print(s)
print(d)

28
[10 11 17 25 39 41 52 71 74 79]
[ 1  6  8 14  2 11 19  3  5]


In [4]:
print(list(range(len(s))))
print(s)
print(np.diff(s))
bm1 = np.array([False] * 10)
bm2 = np.array([False] * 10)
v1 = [6,3]
v2 = [8,1]
for i in range(len(bm1)):
    if i in v1:
        bm1[i] = True
    if i in v2:
        bm2[i] = True
print(f"sum over {s[bm1]}: {np.sum(s[bm1])}")
print(f"sum over {s[bm2]}: {np.sum(s[bm2])}")
#print(list(np.arange(10)[np.invert(bm1|bm2)]))
#print(s[np.invert(bm1|bm2)])
#print(np.diff(s[np.invert(bm1|bm2)]))
a = allConsecSumsOf(np.diff(s))
result_a = sorted((Counter(a) - Counter(set(a))).elements())
print(result_a)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[10 11 17 25 39 41 52 71 74 79]
[ 1  6  8 14  2 11 19  3  5]
sum over [25 52]: 77
sum over [11 74]: 85
[8, 14, 22, 27, 30, 35, 54]


In [5]:
arr = np.diff(s)
sum_target = 3
start = 0
end = len(arr)
print(arr)
print(end)
print(" ")
print(canFindSumInSubarray(arr, sum_target, start, end))

[ 1  6  8 14  2 11 19  3  5]
9
 
True


In [6]:
print(allSumsOf(s))

[0, 10, 11, 17, 21, 25, 27, 28, 35, 36, 38, 39, 41, 42, 46, 49, 50, 51, 52, 52, 52, 53, 56, 58, 60, 62, 62, 63, 63, 64, 66, 66, 67, 68, 69, 69, 71, 73, 74, 74, 75, 76, 77, 77, 77, 79, 79, 79, 80, 80, 81, 81, 82, 83, 84, 85, 85, 87, 87, 88, 88, 89, 90, 90, 90, 91, 91, 91, 91, 92, 92, 93, 93, 94, 94, 95, 96, 96, 97, 98, 98, 99, 99, 100, 101, 101, 101, 102, 102, 102, 103, 104, 104, 104, 104, 105, 105, 106, 106, 107, 107, 107, 108, 108, 109, 109, 110, 110, 110, 112, 112, 112, 113, 113, 114, 114, 115, 115, 115, 115, 116, 116, 116, 117, 117, 118, 118, 118, 118, 119, 120, 120, 120, 120, 121, 121, 121, 122, 122, 123, 123, 123, 123, 124, 124, 125, 125, 126, 126, 126, 126, 126, 127, 127, 127, 128, 128, 129, 129, 129, 129, 130, 130, 131, 131, 131, 131, 131, 132, 132, 132, 132, 133, 133, 133, 133, 134, 134, 134, 135, 135, 135, 136, 136, 137, 137, 137, 137, 137, 137, 138, 138, 139, 139, 139, 140, 140, 140, 140, 141, 141, 141, 142, 142, 142, 142, 143, 143, 143, 143, 143, 143, 144, 144, 145, 145, 145

In [7]:
# Chapter 7

suitmap = {
    0: "Clubs",
    1: "Diamonds",
    2: "Hearts",
    3: "Spades"
}
rankmap = {
    0: "Ace",
    1: "2",
    2: "3",
    3: "4",
    4: "5",
    5: "6",
    6: "7",
    7: "8",
    8: "9",
    9: "10",
    10: "Jack",
    11: "Queen",
    12: "King",
}

In [8]:
c = 0
dh = []
h = []
while c < 5:
    suit = random.randint(0,3)
    rank = random.randint(0,12)
    if rankmap[rank] + " of " + suitmap[suit] not in set(dh):
        dh.append(rankmap[rank] + " of " + suitmap[suit])
        h.append([])
        h[c].append(rank)
        h[c].append(suit)
        c+=1
print(dh)
print(h)

['7 of Hearts', '4 of Spades', '7 of Clubs', '10 of Hearts', '5 of Spades']
[[6, 2], [3, 3], [6, 0], [9, 2], [4, 3]]


In [9]:
# Set

print(checkIfValidArrangement(h, [1,2,4,3,0]))

False


In [10]:
c = 0
dh = []
h = []
while c < 4:
    suit = random.randint(0,3)
    rank = random.randint(0,12)
    if rankmap[rank] + " of " + suitmap[suit] not in set(dh):
        dh.append(rankmap[rank] + " of " + suitmap[suit])
        h.append([])
        h[c].append(rank)
        h[c].append(suit)
        c+=1
print(dh)
#print(h)

['9 of Diamonds', '3 of Diamonds', 'Queen of Clubs', '6 of Clubs']


In [11]:
# Guess

g = "3 of Spades"
rank = list(rankmap.keys())[list(rankmap.values()).index(g.split()[0])]
suit = list(suitmap.keys())[list(suitmap.values()).index(g.split()[2])]
guess = [rank, suit]
hand = [guess] + h
print(checkIfValidArrangement(hand, [0,1,2,3,4]))

False


In [12]:
# Frozone Variation

supersuitmap = {
    0: "Alpha",
    1: "Beta",
    2: "Gamma",
    3: "Spades"
}

def defineCard(inp):
    rank = inp[0]
    suit = inp[1]
    if suit!=3:
        return [rank, suit]
    if rank==0:
        return [0,3]
    s = (rank-1)//4
    sub = 0
    if s==1:
        sub = 4
    if s==2:
        sub = 8
    r = 12+rank-sub
    return [r, s]

def displayCard(card):
    if card[0] < 13:
        suit = str(suitmap[card[1]])
        rank = str(rankmap[card[0]])
    else:
        suit = str(suitmap[3])
        add = -12
        if card[1]==1:
            add += 4
        if card[1]==2:
            add += 8
        rank = str(rankmap[card[0] + add])
    return rank + " of " + suit

In [36]:
c = []
suits = ['C', 'D', 'H', 'S']
ranks = ['A', '2', '3', '4', '5', '6', '7', '8', '9', 'T', 'J', 'Q', 'K']
for i in range(4):
    print(f"Card {i+1}:")
    c.append(input())
    while len(c[i])<2:
        print("Try again:")
        c[i] = input()
    while c[i][0] not in ranks or c[i][1] not in suits or c[i] in c[:-1]:
        print("Try again:")
        c[i] = input()
random.shuffle(c)
#print(c)
cards = []
for i in c:
    cards.append([ranks.index(i[0]), suits.index(i[1])])
#print(cards)
superCards = []
for i in range(len(cards)):
    superCards.append(defineCard(cards[i]))
#print(superCards)
#for i in range(len(superCards)):
    #print(displayCard(superCards[i]))
order = []
faceUp = []
if [0,3] in superCards:
    superCards.remove([0,3])
    order = [0,1,2]
    faceUp = [False,False,False]
else:
    cue = []
    loc1 = -1
    loc2 = -1
    soFar = [superCards[0][1]]
    noDups = True
    i = 1
    while noDups:
        t = superCards[i][1]
        for j in range(len(soFar)):
            if soFar[j]==t:
                noDups = False
                loc1 = j
                loc2 = i
        soFar.append(t)
        i += 1
    #print(f"loc1: {loc1}, loc2: {loc2}")
    increase = (superCards[loc1][0] - superCards[loc2][0]) % 17
    if increase > 8:
        increase = 17 - increase
        superCards.remove(superCards[loc2])
        cue.append(loc1)
    else:
        superCards.remove(superCards[loc1])
        cue.append(loc2-1)
    #print(f"increase: {increase}")
    #print(superCards)
    maxInc = False
    if increase==8:
        maxInc = True
    increase = bin(increase).replace("0b", "")
    while len(increase) < 3:
        increase = "0" + increase
    #print(f"increase in binary: {increase}")
    for i in increase:
        if i=="0":
            faceUp.append(False)
        else:
            faceUp.append(True)
    #print(faceUp)
    t = []
    for i in range(len(superCards)):
        if i!= cue[0]:
            t.append(i)
    if isLowerThan(superCards[t[0]], superCards[t[1]]):
        cue.append(t[0])
        cue.append(t[1])
    else:
        cue.append(t[1])
        cue.append(t[0])
    #print(f"cue: {cue}")
    for i in range(len(faceUp)):
        if faceUp[i]:
            order.append(cue[0])
            cue.pop(0)
        else:
            order.append(cue[-1])
            cue.pop(-1)
#print(f"order: {order}")
#print(f"faceUp: {faceUp}")
positions = {
    0: "On the left",
    1: "In the middle",
    2: "On the right"
}
print(" ")
for i in range(len(superCards)):
    way = "down"
    if faceUp[i]:
        way = "up"
    print(f"{positions[i]}: {displayCard(superCards[order[i]])}, face {way}")

Card 1:
AS
Card 2:
7H
Card 3:
4C
Card 4:
TC
 
On the left: 7 of Hearts, face down
In the middle: 10 of Clubs, face down
On the right: 4 of Clubs, face down
